version: '3.9'

networks:
  default:
    name: 'postershared'

volumes:
  api-logs-os:
  api-logs-osd:

services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: api-logs-os
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true' 
    volumes:
      - api-logs-os:/usr/share/opensearch/data3
        
  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: api-logs-osd
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://api-logs-os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch
