version: '3.9'

services:
  background:
    image: evilvegetarian/telegrambackground:##BuildNumber##
    ports:
       - target: 8080
         published: 10001
    volumes:
      - ./appsettings.json:/app/appsettings.json