version: '3.9'

services:
  telegramposter.api:
    image: evilvegetarian/telegramposter:##BuildNumber##
    ports:
       - target: 8080
         published: 10000
    volumes:
      - ./appsettings.json:/app/appsettings.json