name: DeployApi

on:
  workflow_dispatch:
  push:
    branches: 
    - master
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Replace file content
      run: (Get-Content TelegramPoster.Api/appsettings.Production.json) -replace '##BuildNumber##', '${{ github.run_number }}' | Set-Content TelegramPoster.Api/appsettings.Production.json
      shell: pwsh

    - name: Replace file content
      run: (Get-Content docker-compose.yml) -replace '##BuildNumber##', '${{ github.run_number }}' | Set-Content docker-compose.yml
      shell: pwsh
          
    # Log in to Docker Hub before pushing the image
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: TelegramPoster.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REP }}:${{ github.run_number }}

    # Copy docker-compose file to the server
    - name: Copy docker-compose file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.PASSWORD }}
        source: docker-compose.yml
        target: /root/TelegramPosterApp/TelegramApi/

    # Deploy on the server
    - name: Deploy on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /root/TelegramPosterApp/TelegramApi/
          docker-compose down
          docker pull ${{ secrets.DOCKER_REP }}:${{ github.run_number }}
          docker-compose up -d 
          docker image prune -f
